FROM python:3.11-slim

WORKDIR /app

COPY requirements-frontend.txt /tmp/requirements-frontend.txt
RUN pip install --no-cache-dir -r /tmp/requirements-frontend.txt

COPY frontend /app/frontend

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app.py", "--server.address=0.0.0.0", "--server.port=8501"]

