"""
Kafka producer for welding sensor CSV replay.

Scenario
--------
There is no live sensor API in this assignment. Instead, each production line
is assumed to create one product's CSV files every 10 seconds. This producer
replays those CSV files as if they were newly generated by line PCs/NAS devices,
groups Laser A and Laser B into product instances, splits each signal into
chunks, and publishes the chunks to Kafka topic `welding.raw.v1`.

Run examples
------------
python producer.py --data-dir ./data --kafka localhost:29092 --speed 50
python producer.py --data-dir ./data --target-products 2000 --speed 100
python producer.py --data-dir ./data --dry-run

강사님께 설명할 핵심 흐름
------------------------
1. 실제 센서 API가 없으므로 CSV가 생산라인별로 10초마다 생성된다고 가정한다.
2. data 폴더를 스캔해서 한 제품의 laser_b(MASKED_CH) / laser_a(MASKED_CH) CSV를 묶는다.
3. 큰 신호 배열을 chunk 단위로 나눠 Kafka 메시지 크기를 안정적으로 유지한다.
4. line_id + product_instance_id + lead + laser를 key로 사용해 같은 신호의 순서를 보장한다.
5. --line-count로 생산라인을 늘려도 라인별 key가 분리되므로 Kafka가 병렬 처리할 수 있다.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import re
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterable

import numpy as np
from kafka import KafkaProducer
from kafka.errors import KafkaError, NoBrokersAvailable


LOG_FORMAT = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
logging.basicConfig(level=logging.INFO, format=LOG_FORMAT, datefmt="%H:%M:%S")
logger = logging.getLogger("welding.producer")


TOPIC_RAW = os.getenv("TOPIC_RAW", "welding.raw.v1")
DEFAULT_KAFKA = os.getenv("KAFKA_BOOTSTRAP", "localhost:29092")
DEFAULT_CHUNK_SIZE = int(os.getenv("CHUNK_SIZE", "5000"))
SAMPLE_RATE_HZ = int(os.getenv("SAMPLE_RATE_HZ", "25000"))
MAX_REQUEST_SIZE = int(os.getenv("MAX_REQUEST_SIZE", "5242880"))
PRODUCER_VERSION = "v1"


# 제출용 긴 파일명과 현재 보유 데이터셋의 짧은 파일명을 모두 지원한다.
# 긴 파일명 예: 20220417_000442_1_WLINE_01_04_PROD_001_01_LB.csv
FILE_RE = re.compile(
    r"(?P<date>\d{8})_(?P<time>\d{6})_(?P<seq>\d+)_"
    r"(?P<line>[A-Za-z0-9]+)_(?P<batch>\d{2})_(?P<product_id>[A-Za-z0-9_-]+)_"
    r"(?P<lead_num>\d{2})_(?:(?:CH(?P<channel>[01]))|(?P<laser_id>L[AB]))\.csv$"
)
SIMPLE_FILE_RE = re.compile(
    r"(?P<date>\d{8})_battery_(?P<battery_id>\d+)_"
    r"(?:(?:CH(?P<channel>[01]))|(?P<laser>laser_[ab]))\.csv$"
)
# internal_mapping.md 기준: MASKED_CH은 laser_b/LB, MASKED_CH은 laser_a/LA이다.
LASER_NAME_TO_CHANNEL = {"laser_b": 0, "laser_a": 1}
LASER_ID_TO_CHANNEL = {"LB": 0, "LA": 1}


def parse_event_time(date_text: str, time_text: str) -> datetime:
    return datetime.strptime(
        f"{date_text}{time_text}", "%Y%m%d%H%M%S"
    ).replace(tzinfo=timezone.utc)


def isoformat_z(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


def lead_type_from_num(lead_num: int) -> str:
    return "AL_CU" if lead_num % 2 == 1 else "CU_CU"


def channel_code(channel: int) -> str:
    return "LB" if channel == 0 else "LA"


def channel_name(channel: int) -> str:
    return "LaserB" if channel == 0 else "LaserA"


@dataclass
class ProductRecord:
    """One physical product instance produced by one welding line."""

    # ProductRecord는 스캔 단계에서 만든 "원본 제품 1개"의 메타데이터와 CSV 경로 묶음이다.
    product_instance_id: str
    product_id: str
    line_id: str
    batch_id: str
    sequence_id: str
    event_time: datetime
    # files[channel][lead_num] = CSV path 형태로 저장해 두면 발행 단계에서 채널 순서대로 꺼낼 수 있다.
    files: dict[int, dict[int, Path]] = field(
        default_factory=lambda: {0: {}, 1: {}}
    )

    def add_file(self, lead_num: int, channel: int, path: Path) -> None:
        self.files[channel][lead_num] = path

    @property
    def leads_present(self) -> set[int]:
        return set(self.files[0].keys()) | set(self.files[1].keys())

    @property
    def channel_pairs(self) -> int:
        return len(set(self.files[0].keys()) & set(self.files[1].keys()))

    @property
    def is_complete(self) -> bool:
        return self.channel_pairs >= 16


@dataclass
class PublishItem:
    # PublishItem은 실제 Kafka로 보낼 1개 제품 이벤트이다.
    # 같은 원본 CSV도 line_id나 product_instance_id를 바꿔 여러 생산라인 데이터처럼 replay할 수 있다.
    record: ProductRecord
    product_instance_id: str
    line_id: str
    event_time: datetime
    is_duplicate: bool = False
    original_product_instance_id: str | None = None
    replay_iteration: int = 0


def build_instance_id(parts: dict[str, str]) -> str:
    return (
        f"{parts['date']}_{parts['time']}_{parts['seq']}_"
        f"{parts['line']}_{parts['batch']}_{parts['product_id']}"
    )


def scan_data_dir(data_dir: str) -> list[ProductRecord]:
    """Scan CSV files and group them into line/product instances."""
    root = Path(data_dir)
    if not root.exists():
        raise FileNotFoundError(f"data directory does not exist: {data_dir}")

    records: dict[str, ProductRecord] = {}
    ignored = 0

    for csv_path in sorted(root.glob("**/*.csv")):
        # 1순위: 제출 문서의 정식 파일명 규칙을 파싱한다.
        match = FILE_RE.match(csv_path.name)
        if match:
            parts = match.groupdict()
            instance_id = build_instance_id(parts)
            lead_num = int(parts["lead_num"])
            channel = (
                LASER_ID_TO_CHANNEL[parts["laser_id"]]
                if parts.get("laser_id")
                else int(parts["channel"])
            )
            product_id = parts["product_id"]
            line_id = parts["line"]
            batch_id = parts["batch"]
            sequence_id = parts["seq"]
            event_time = parse_event_time(parts["date"], parts["time"])
        else:
            # 2순위: 현재 데이터셋의 짧은 파일명 규칙을 파싱한다.
            # 예: 20220417_battery_10_laser_b.csv
            simple_match = SIMPLE_FILE_RE.match(csv_path.name)
            if not simple_match:
                ignored += 1
                continue

            parts = simple_match.groupdict()
            channel = (
                LASER_NAME_TO_CHANNEL[parts["laser"].lower()]
                if parts.get("laser")
                else int(parts["channel"])
            )

            lead_num = 1
            product_id = f"battery_{int(parts['battery_id'])}"
            # 현재 샘플 데이터는 라인 정보가 파일명에 없으므로 기본 라인으로 시작한다.
            # --line-count 옵션을 쓰면 발행 단계에서 LINE_01, LINE_02처럼 확장된다.
            line_id = "LINE_01"
            batch_id = parts["date"]
            sequence_id = parts["battery_id"]
            instance_id = f"{parts['date']}_{product_id}"
            event_time = parse_event_time(parts["date"], "000000")

        if instance_id not in records:
            # 같은 product_instance_id 아래에 laser_b와 laser_a CSV를 계속 모은다.
            records[instance_id] = ProductRecord(
                product_instance_id=instance_id,
                product_id=product_id,
                line_id=line_id,
                batch_id=batch_id,
                sequence_id=sequence_id,
                event_time=event_time,
            )

        records[instance_id].add_file(lead_num, channel, csv_path)

    result = sorted(records.values(), key=lambda r: (r.event_time, r.line_id, r.product_instance_id))
    logger.info(
        "Scanned %s product instances from %s. complete=%s ignored_files=%s",
        len(result),
        data_dir,
        sum(1 for r in result if r.is_complete),
        ignored,
    )
    return result


def load_signal(path: Path) -> np.ndarray:
    """
    Load one CSV signal as float32.

    The expected format is one numeric column. If multiple numeric columns are
    present, the last column is used because exported measurement files often
    include an index/time column before the signal column.
    """
    data = np.genfromtxt(str(path), delimiter=",", dtype=np.float32)
    if data.size == 0:
        raise ValueError("empty signal file")

    if data.ndim == 2:
        data = data[:, -1]

    data = np.asarray(data, dtype=np.float32).reshape(-1)
    data = data[np.isfinite(data)]
    if data.size == 0:
        raise ValueError("no finite numeric samples")
    return data


def make_message(
    item: PublishItem,
    lead_num: int,
    channel: int,
    file_path: Path,
    samples: np.ndarray,
    chunk_index: int,
    chunk_size: int,
    total_chunks: int,
) -> dict:
    start = chunk_index * chunk_size
    end = min(start + chunk_size, len(samples))
    chan_code = channel_code(channel)
    # message_id는 Consumer/DB에서 중복 저장을 막기 위한 결정론적 id이다.
    message_id = (
        f"{item.product_instance_id}:L{lead_num:02d}:"
        f"{chan_code}:{chunk_index:06d}"
    )

    return {
        "message_id": message_id,
        "product_instance_id": item.product_instance_id,
        "product_id": item.record.product_id,
        "line_id": item.line_id,
        "batch_id": item.record.batch_id,
        "sequence_id": item.record.sequence_id,
        "lead_num": lead_num,
        "lead_type": lead_type_from_num(lead_num),
        "channel": channel,
        "channel_name": channel_name(channel),
        "chunk_index": chunk_index,
        "total_chunks": total_chunks,
        "is_last_chunk": chunk_index == total_chunks - 1,
        "sample_rate_hz": SAMPLE_RATE_HZ,
        "start_sample": start,
        "end_sample": end,
        "samples": samples[start:end].tolist(),
        "event_time": isoformat_z(item.event_time),
        "metadata": {
            "source": "file_replay_producer",
            "version": PRODUCER_VERSION,
            "file_name": file_path.name,
            "original_product_instance_id": item.original_product_instance_id
            or item.record.product_instance_id,
            "is_duplicate": item.is_duplicate,
            "replay_iteration": item.replay_iteration,
        },
    }


def build_producer(kafka_bootstrap: str, retries: int = 8) -> KafkaProducer:
    """Create KafkaProducer with at-least-once delivery settings."""
    last_error: Exception | None = None

    for attempt in range(1, retries + 1):
        try:
            producer = KafkaProducer(
                bootstrap_servers=kafka_bootstrap,
                # acks=all은 broker가 저장 확인을 줄 때까지 성공 처리하지 않아 유실 가능성을 낮춘다.
                acks="all",
                # 일시적인 broker/network 문제는 Producer가 자동 재시도한다.
                retries=10,
                retry_backoff_ms=500,
                request_timeout_ms=30000,
                # 같은 연결에서 여러 요청이 앞질러 가는 것을 막아 chunk 순서 설명이 쉬워진다.
                max_in_flight_requests_per_connection=1,
                compression_type=os.getenv("KAFKA_COMPRESSION", "gzip"),
                linger_ms=20,
                batch_size=65536,
                max_request_size=MAX_REQUEST_SIZE,
                key_serializer=lambda value: value.encode("utf-8"),
                value_serializer=lambda value: json.dumps(
                    value, ensure_ascii=False, separators=(",", ":")
                ).encode("utf-8"),
            )
            logger.info("Connected to Kafka bootstrap=%s", kafka_bootstrap)
            return producer
        except NoBrokersAvailable as exc:
            last_error = exc
            logger.warning(
                "Kafka is not ready. attempt=%s/%s bootstrap=%s",
                attempt,
                retries,
                kafka_bootstrap,
            )
            time.sleep(3)

    raise RuntimeError(f"failed to connect to Kafka: {last_error}")


def on_send_success(metadata) -> None:
    logger.debug(
        "sent topic=%s partition=%s offset=%s",
        metadata.topic,
        metadata.partition,
        metadata.offset,
    )


def on_send_error(exc: KafkaError) -> None:
    logger.error("Kafka send failed: %s", exc)


def make_publish_items(
    records: list[ProductRecord],
    target_products: int,
    max_products: int | None,
    line_count: int,
    line_interval_seconds: float,
) -> list[PublishItem]:
    """Create line-aware replay items for demo/load-test scenarios."""
    selected = records[:max_products] if max_products else records
    if not selected:
        return []

    if line_count < 1:
        raise ValueError("line_count must be >= 1")

    total_products = target_products if target_products > 0 else len(selected) * line_count
    items: list[PublishItem] = []
    base_event_time = selected[0].event_time

    for index in range(total_products):
        # index를 라인 수로 나눠 같은 원본 제품을 여러 생산라인에서 나온 데이터처럼 분산한다.
        line_index = index % line_count
        product_index = index // line_count
        source = selected[product_index % len(selected)]
        line_id = source.line_id if line_count == 1 else f"LINE_{line_index + 1:02d}"
        is_replay = product_index >= len(selected) or line_id != source.line_id
        replay_no = product_index // len(selected)
        product_instance_id = (
            source.product_instance_id
            if not is_replay
            else f"{source.product_instance_id}_{line_id}_R{replay_no:05d}"
        )

        items.append(
            PublishItem(
                record=source,
                product_instance_id=product_instance_id,
                line_id=line_id if is_replay else source.line_id,
                # 실제 센서 API 대신 각 생산라인이 10초마다 새 CSV를 생성한다고 가정한다.
                # 같은 product_index의 여러 라인은 같은 시각에 병렬로 데이터가 생긴다.
                event_time=base_event_time
                + timedelta(seconds=product_index * line_interval_seconds),
                is_duplicate=is_replay,
                original_product_instance_id=source.product_instance_id,
                replay_iteration=replay_no,
            )
        )

    return sorted(items, key=lambda item: (item.event_time, item.line_id, item.product_instance_id))


def publish_product(
    producer: KafkaProducer,
    item: PublishItem,
    topic: str,
    chunk_size: int,
    speed: float,
) -> int:
    """Publish all available leads/channels for one product instance."""
    sent = 0
    record = item.record

    for lead_num in sorted(record.leads_present):
        # 한 제품 안에서 laser_b(channel 0), laser_a(channel 1)를 순서대로 발행한다.
        for channel in (0, 1):
            file_path = record.files[channel].get(lead_num)
            if file_path is None:
                logger.warning(
                    "Missing channel. product=%s lead=%s channel=%s",
                    item.product_instance_id,
                    lead_num,
                    channel,
                )
                continue

            try:
                signal = load_signal(file_path)
            except Exception as exc:
                logger.error("Failed to load %s: %s", file_path, exc)
                continue

            total_chunks = max(1, int(np.ceil(len(signal) / chunk_size)))
            chan_code = channel_code(channel)
            # partition key에 line/product/lead/laser를 넣어 같은 신호의 chunk가 같은 파티션에 쌓이게 한다.
            partition_key = (
                f"{item.line_id}_{item.product_instance_id}_"
                f"L{lead_num:02d}_{chan_code}"
            )

            for chunk_index in range(total_chunks):
                # 큰 CSV 전체를 한 메시지로 보내지 않고 chunk로 나눠 broker/message size 부담을 줄인다.
                message = make_message(
                    item=item,
                    lead_num=lead_num,
                    channel=channel,
                    file_path=file_path,
                    samples=signal,
                    chunk_index=chunk_index,
                    chunk_size=chunk_size,
                    total_chunks=total_chunks,
                )
                producer.send(topic, key=partition_key, value=message).add_callback(
                    on_send_success
                ).add_errback(on_send_error)
                sent += 1

                if speed > 0:
                    # speed는 "제품 간격"이 아니라 한 제품 내부 신호 chunk의 재생 속도이다.
                    delay_seconds = (chunk_size / SAMPLE_RATE_HZ) / speed
                    if delay_seconds >= 0.002:
                        time.sleep(delay_seconds)

    return sent


def run(args: argparse.Namespace) -> int:
    # 실행 흐름: 스캔 -> replay 목록 생성 -> dry-run 출력 또는 Kafka 발행.
    records = scan_data_dir(args.data_dir)
    if args.only_complete:
        records = [record for record in records if record.is_complete]
        logger.info("Filtered to complete product instances: %s", len(records))

    if not records:
        logger.error("No matching product files found.")
        return 2

    items = make_publish_items(
        records=records,
        target_products=args.target_products,
        max_products=args.max_products,
        line_count=args.line_count,
        line_interval_seconds=args.line_interval_seconds,
    )

    if args.dry_run:
        original_count = sum(1 for item in items if not item.is_duplicate)
        duplicate_count = sum(1 for item in items if item.is_duplicate)
        lines = sorted({item.line_id for item in items})
        print("Dry run summary")
        print(f"- data_dir: {args.data_dir}")
        print(f"- product_instances: {len(items)}")
        print(f"- originals: {original_count}")
        print(f"- duplicates: {duplicate_count}")
        print(f"- lines: {', '.join(lines)}")
        print(f"- line_count: {args.line_count}")
        print(f"- line_interval_seconds: {args.line_interval_seconds}")
        print(f"- topic: {args.topic}")
        return 0

    producer = build_producer(args.kafka)

    try:
        while True:
            total_messages = 0
            first_event_time = items[0].event_time
            started_at = time.monotonic()
            for index, item in enumerate(items, start=1):
                if not args.no_schedule_wait:
                    # event_time 차이를 wall-clock 대기로 바꿔
                    # "각 생산라인에서 10초마다 CSV 생성" 상황을 시뮬레이션한다.
                    scheduled_after = (
                        item.event_time - first_event_time
                    ).total_seconds()
                    wait_seconds = scheduled_after - (time.monotonic() - started_at)
                    if wait_seconds > 0:
                        time.sleep(wait_seconds)

                sent = publish_product(
                    producer=producer,
                    item=item,
                    topic=args.topic,
                    chunk_size=args.chunk_size,
                    speed=args.speed,
                )
                total_messages += sent
                logger.info(
                    "[%s/%s] product=%s line=%s duplicate=%s messages=%s",
                    index,
                    len(items),
                    item.product_instance_id,
                    item.line_id,
                    item.is_duplicate,
                    sent,
                )

            producer.flush()
            # flush 이후 종료해야 Python 프로세스가 끝나기 전에 buffered message가 모두 전송된다.
            logger.info("Run complete. total_messages=%s", total_messages)

            if not args.loop:
                break
            logger.info("Loop mode enabled. Restarting replay in 5 seconds.")
            time.sleep(5)
    except KeyboardInterrupt:
        logger.info("Interrupted by user.")
    finally:
        producer.flush()
        producer.close()
        logger.info("Producer closed.")

    return 0


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    # CLI 옵션은 실험 조건을 바꾸는 부분이다. 코드 수정 없이 라인 수/속도/목표 제품 수를 조절한다.
    parser = argparse.ArgumentParser(
        description="Welding CSV to Kafka producer",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--data-dir", required=True, help="CSV root directory")
    parser.add_argument("--kafka", default=DEFAULT_KAFKA, help="Kafka bootstrap server")
    parser.add_argument("--topic", default=TOPIC_RAW, help="Kafka topic")
    parser.add_argument("--chunk-size", type=int, default=DEFAULT_CHUNK_SIZE)
    parser.add_argument("--speed", type=float, default=50.0, help="Replay speed multiplier")
    parser.add_argument(
        "--line-count",
        type=int,
        default=1,
        help="Number of production lines to simulate",
    )
    parser.add_argument(
        "--line-interval-seconds",
        type=float,
        default=10.0,
        help="Seconds between products from each production line",
    )
    parser.add_argument(
        "--no-schedule-wait",
        action="store_true",
        help="Do not wait for the simulated line interval; publish as fast as chunk speed allows",
    )
    parser.add_argument(
        "--target-products",
        type=int,
        default=0,
        help="Replay duplicate product instances until this count is reached",
    )
    parser.add_argument(
        "--max-products",
        type=int,
        default=None,
        help="Limit original product instances for a short demo",
    )
    parser.add_argument(
        "--only-complete",
        action="store_true",
        help="Publish only products with 16 Laser A/B lead pairs",
    )
    parser.add_argument("--loop", action="store_true", help="Replay continuously")
    parser.add_argument("--dry-run", action="store_true", help="Scan and print summary only")
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(run(parse_args()))

