"""
Kafka producer for welding sensor CSV replay.

Scenario
--------
There is no live sensor API in this assignment. Instead, each production line
is assumed to create one product's CSV files every 10 seconds. This producer
replays those CSV files as if they were newly generated by line PCs/NAS devices,
groups Laser A and Laser B into product instances, splits each signal into
chunks, and publishes the chunks to Kafka topic `welding.raw.v1`.

Run examples
------------
python producer.py --kafka localhost:29092 --speed 50
python producer.py --target-products 2000 --speed 100
python producer.py --dry-run

강사님께 설명할 핵심 흐름
------------------------
1. 실제 센서 API가 없으므로 CSV가 생산라인별로 10초마다 생성된다고 가정한다.
2. data 폴더를 스캔해서 한 제품의 laser_b(MASKED_CH) / laser_a(MASKED_CH) CSV를 묶는다.
3. 큰 신호 배열을 chunk 단위로 나눠 Kafka 메시지 크기를 안정적으로 유지한다.
4. line_id + product_instance_id + lead + laser를 key로 사용해 같은 신호의 순서를 보장한다.
5. --line-count로 생산라인을 늘려도 라인별 key가 분리되므로 Kafka가 병렬 처리할 수 있다.
"""

from __future__ import annotations

import argparse
import random
import json
import logging
import os
import re
import sys
import time
import hashlib
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterable

import numpy as np
from kafka import KafkaProducer
from kafka.errors import KafkaError, NoBrokersAvailable


def load_env_file(path: str = ".env") -> None:
    """Load local .env values without adding an external dependency."""
    env_path = Path(path)
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


load_env_file()


LOG_FORMAT = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
logging.basicConfig(level=logging.INFO, format=LOG_FORMAT, datefmt="%H:%M:%S")
logger = logging.getLogger("welding.producer")


def setup_file_logger(storage_dir: str | None) -> None:
    if not storage_dir:
        storage_dir = str(Path.cwd() / "storage")
    log_dir = Path(storage_dir) / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    log_file = log_dir / "producer.log"
    
    # 중복 추가 방지
    if any(isinstance(h, logging.FileHandler) for h in logger.handlers):
        return

    file_handler = logging.FileHandler(log_file, encoding="utf-8")
    file_handler.setFormatter(logging.Formatter(LOG_FORMAT, datefmt="%H:%M:%S"))
    logger.addHandler(file_handler)
    logger.info("File logging enabled: %s", log_file)


DEFAULT_DATA_DIR = os.getenv("DATA_DIR") or None
DEFAULT_STORAGE_DIR = os.getenv("STORAGE_DIR") or None
TOPIC_RAW = os.getenv("TOPIC_RAW", "welding.raw.v1")
TOPIC_RAW_LASER_A = os.getenv("TOPIC_RAW_LASER_A", "")
TOPIC_RAW_LASER_B = os.getenv("TOPIC_RAW_LASER_B", "")
DEFAULT_KAFKA = os.getenv("KAFKA_BOOTSTRAP", "localhost:29092")
DEFAULT_CHUNK_SIZE = int(os.getenv("CHUNK_SIZE", "5000"))
TARGET_CHUNK_BYTES = int(os.getenv("TARGET_CHUNK_BYTES", "900000"))
MAX_CHUNKS_PER_SIGNAL = int(os.getenv("MAX_CHUNKS_PER_SIGNAL", "2048"))
SAMPLE_RATE_HZ = int(os.getenv("SAMPLE_RATE_HZ", "25000"))
MAX_REQUEST_SIZE = int(os.getenv("MAX_REQUEST_SIZE", "5242880"))
PRODUCER_VERSION = "v1"


# 제출용 긴 파일명과 현재 보유 데이터셋의 짧은 파일명을 모두 지원한다.
# 긴 파일명 예: 20220417_000442_1_WLINE_01_04_PROD_001_01_LB.csv
FILE_RE = re.compile(
    r"(?P<date>\d{8})_(?P<time>\d{6})_(?P<seq>\d+)_"
    r"(?P<line>[A-Za-z0-9]+)_(?P<batch>\d{2})_(?P<product_id>[A-Za-z0-9_-]+)_"
    r"(?P<lead_num>\d{2})_(?:(?:CH(?P<channel>[01]))|(?P<laser_id>L[AB]))\.csv$"
)
SIMPLE_FILE_RE = re.compile(
    r"(?P<date>\d{8})_battery_(?P<battery_id>\d+)_"
    r"(?:(?:CH(?P<channel>[01]))|(?P<laser>laser_[ab]))\.csv$"
)
# internal_mapping.md 기준: MASKED_CH은 laser_b/LB, MASKED_CH은 laser_a/LA이다.
LASER_NAME_TO_CHANNEL = {"laser_b": 0, "laser_a": 1}
LASER_ID_TO_CHANNEL = {"LB": 0, "LA": 1}
# internal_mapping.md 기준:
#   MASKED_CH = 반사광(Reflected) = LaserB = channel 0
#   MASKED_CH = 출사광(Emitted)   = LaserA = channel 1
# concat_out_0       : 출사광(LaserA) CSV 묶음 → channel 1
# concat_reflected_1 : 반사광(LaserB) CSV 묶음 → channel 0
CHANNEL_FOLDER_TO_CHANNEL = {
    "concat_out_0": 1,
    "concat_reflected_1": 0,
    "reflect": 0,
    "laser_b": 0,
    "out": 1,
    "laser_a": 1,
}
DATE_RE = re.compile(r"^\d{8}$")
TRAILING_CHANNEL_RE = re.compile(r"_(?:CH[01]|laser_[ab]|L[AB])$", re.IGNORECASE)
TRAILING_DIGITS_RE = re.compile(r"(\d+)$")


def parse_event_time(date_text: str, time_text: str) -> datetime:
    return datetime.strptime(
        f"{date_text}{time_text}", "%Y%m%d%H%M%S"
    ).replace(tzinfo=timezone.utc)


def isoformat_z(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


def lead_type_from_num(lead_num: int) -> str:
    return "AL_CU" if lead_num % 2 == 1 else "CU_CU"


def channel_code(channel: int) -> str:
    return "LB" if channel == 0 else "LA"


def channel_name(channel: int) -> str:
    return "LaserB" if channel == 0 else "LaserA"


@dataclass
class ProductRecord:
    """One physical product instance produced by one welding line."""

    # ProductRecord는 스캔 단계에서 만든 "원본 제품 1개"의 메타데이터와 CSV 경로 묶음이다.
    product_instance_id: str
    product_id: str
    line_id: str
    batch_id: str
    sequence_id: str
    event_time: datetime
    # files[channel][lead_num] = CSV path 형태로 저장해 두면 발행 단계에서 채널 순서대로 꺼낼 수 있다.
    files: dict[int, dict[int, Path]] = field(
        default_factory=lambda: {0: {}, 1: {}}
    )

    def add_file(self, lead_num: int, channel: int, path: Path) -> None:
        self.files[channel][lead_num] = path

    @property
    def leads_present(self) -> set[int]:
        return set(self.files[0].keys()) | set(self.files[1].keys())

    @property
    def channel_pairs(self) -> int:
        return len(set(self.files[0].keys()) & set(self.files[1].keys()))

    @property
    def is_complete(self) -> bool:
        return self.channel_pairs >= 16


@dataclass
class PublishItem:
    # PublishItem은 실제 Kafka로 보낼 1개 제품 이벤트이다.
    # 같은 원본 CSV도 line_id나 product_instance_id를 바꿔 여러 생산라인 데이터처럼 replay할 수 있다.
    record: ProductRecord
    product_instance_id: str
    line_id: str
    line_number: int
    event_time: datetime
    is_duplicate: bool = False
    original_product_instance_id: str | None = None
    replay_iteration: int = 0


def build_instance_id(parts: dict[str, str]) -> str:
    return (
        f"{parts['date']}_{parts['time']}_{parts['seq']}_"
        f"{parts['line']}_{parts['batch']}_{parts['product_id']}"
    )


def infer_date_from_path(root: Path, csv_path: Path) -> str | None:
    for path_part in csv_path.relative_to(root).parts:
        if DATE_RE.match(path_part):
            return path_part
    return None


def infer_channel_from_path(root: Path, csv_path: Path) -> int | None:
    for path_part in csv_path.relative_to(root).parts:
        channel = CHANNEL_FOLDER_TO_CHANNEL.get(path_part.lower())
        if channel is not None:
            return channel
    return None


def product_id_from_stem(stem: str) -> str:
    return TRAILING_CHANNEL_RE.sub("", stem)


def line_number_from_line_id(line_id: str) -> int:
    matched = TRAILING_DIGITS_RE.search(line_id or "")
    if matched:
        return int(matched.group(1))
    return 1


def scan_data_dir(data_dir: str) -> list[ProductRecord]:
    """Scan CSV files and group them into line/product instances."""
    root = Path(data_dir)
    if not root.exists():
        raise FileNotFoundError(f"data directory does not exist: {data_dir}")

    records: dict[str, ProductRecord] = {}
    ignored = 0

    for csv_path in sorted(root.glob("**/*.csv")):
        # 1순위: 제출 문서의 정식 파일명 규칙을 파싱한다.
        folder_channel = infer_channel_from_path(root, csv_path)
        match = FILE_RE.match(csv_path.name)
        if match:
            parts = match.groupdict()
            instance_id = build_instance_id(parts)
            lead_num = int(parts["lead_num"])
            channel = (
                LASER_ID_TO_CHANNEL[parts["laser_id"]]
                if parts.get("laser_id")
                else int(parts["channel"])
            )
            if folder_channel is not None:
                channel = folder_channel
            product_id = parts["product_id"]
            line_id = parts["line"]
            batch_id = parts["batch"]
            sequence_id = parts["seq"]
            event_time = parse_event_time(parts["date"], parts["time"])
        else:
            # 2순위: 현재 데이터셋의 짧은 파일명 규칙을 파싱한다.
            # 예: 20220417_battery_10_laser_b.csv
            simple_match = SIMPLE_FILE_RE.match(csv_path.name)
            if simple_match:
                parts = simple_match.groupdict()
                channel = (
                    LASER_NAME_TO_CHANNEL[parts["laser"].lower()]
                    if parts.get("laser")
                    else int(parts["channel"])
                )
                if folder_channel is not None:
                    channel = folder_channel

                lead_num = 1
                product_id = f"battery_{int(parts['battery_id'])}"
                # 현재 샘플 데이터는 라인 정보가 파일명에 없으므로 기본 라인으로 시작한다.
                # --line-count 옵션을 쓰면 발행 단계에서 LINE_01, LINE_02처럼 확장된다.
                line_id = "LINE_01"
                batch_id = parts["date"]
                sequence_id = parts["battery_id"]
                instance_id = f"{parts['date']}_{product_id}"
                event_time = parse_event_time(parts["date"], "000000")
            else:
                # 3순위: DATA_DIR\{date}\out|reflect\*.csv 구조를 지원한다.
                # 폴더명이 채널을 알려주면 파일명은 제품 id로 사용한다.
                data_date = infer_date_from_path(root, csv_path)
                if folder_channel is None or data_date is None:
                    ignored += 1
                    continue

                channel = folder_channel
                lead_num = 1
                product_id = product_id_from_stem(csv_path.stem)
                line_id = "LINE_01"
                batch_id = data_date
                sequence_id = product_id
                instance_id = f"{data_date}_{product_id}"
                event_time = parse_event_time(data_date, "000000")

        if instance_id not in records:
            # 같은 product_instance_id 아래에 laser_b와 laser_a CSV를 계속 모은다.
            records[instance_id] = ProductRecord(
                product_instance_id=instance_id,
                product_id=product_id,
                line_id=line_id,
                batch_id=batch_id,
                sequence_id=sequence_id,
                event_time=event_time,
            )

        records[instance_id].add_file(lead_num, channel, csv_path)

    result = sorted(records.values(), key=lambda r: (r.event_time, r.line_id, r.product_instance_id))
    logger.info(
        "Scanned %s product instances from %s. complete=%s ignored_files=%s",
        len(result),
        data_dir,
        sum(1 for r in result if r.is_complete),
        ignored,
    )
    return result


def load_signal(path: Path) -> np.ndarray:
    """
    Load one CSV signal as float32.

    The expected format is one numeric column. If multiple numeric columns are
    present, the last column is used because exported measurement files often
    include an index/time column before the signal column.
    """
    data = np.genfromtxt(str(path), delimiter=",", dtype=np.float32)
    if data.size == 0:
        raise ValueError("empty signal file")

    if data.ndim == 2:
        data = data[:, -1]

    data = np.asarray(data, dtype=np.float32).reshape(-1)
    data = data[np.isfinite(data)]
    if data.size == 0:
        raise ValueError("no finite numeric samples")
    return data


def make_message(
    item: PublishItem,
    lead_num: int,
    channel: int,
    file_path: Path,
    samples: np.ndarray,
    chunk_index: int,
    total_chunks: int,
    chunk_size: int | None = None,
    chunk_start: int | None = None,
    chunk_end: int | None = None,
) -> dict:
    if chunk_start is None:
        if chunk_size is None:
            raise ValueError("chunk_size is required when chunk_start is not provided")
        chunk_start = chunk_index * chunk_size
    if chunk_end is None:
        if chunk_size is None:
            raise ValueError("chunk_size is required when chunk_end is not provided")
        chunk_end = min(chunk_start + chunk_size, len(samples))

    start = int(chunk_start)
    end = int(chunk_end)
    chunk_values = np.asarray(samples[start:end], dtype=np.float32)
    chunk_checksum = hashlib.sha1(chunk_values.tobytes()).hexdigest()
    chan_code = channel_code(channel)
    # message_id는 Consumer/DB에서 중복 저장을 막기 위한 결정론적 id이다.
    message_id = (
        f"{item.product_instance_id}:L{lead_num:02d}:"
        f"{chan_code}:{chunk_index:06d}"
    )
    prefixed_file_name = f"{item.line_number}_{file_path.name}"

    return {
        "message_id": message_id,
        "product_instance_id": item.product_instance_id,
        "product_id": item.record.product_id,
        "line_id": item.line_id,
        "batch_id": item.record.batch_id,
        "sequence_id": item.record.sequence_id,
        "lead_num": lead_num,
        "lead_type": lead_type_from_num(lead_num),
        "channel": channel,
        "channel_name": channel_name(channel),
        "chunk_index": chunk_index,
        "total_chunks": total_chunks,
        "is_last_chunk": chunk_index == total_chunks - 1,
        "sample_rate_hz": SAMPLE_RATE_HZ,
        "start_sample": start,
        "end_sample": end,
        "samples": chunk_values.tolist(),
        "event_time": isoformat_z(item.event_time),
        "metadata": {
            "source": "file_replay_producer",
            "version": PRODUCER_VERSION,
            "file_name": prefixed_file_name,
            "original_product_instance_id": item.original_product_instance_id
            or item.record.product_instance_id,
            "is_duplicate": item.is_duplicate,
            "replay_iteration": item.replay_iteration,
            "chunk_checksum": chunk_checksum,
        },
    }


def _json_token_size(sample: float) -> int:
    """Return utf-8 byte size for one JSON float token."""
    return len(
        json.dumps(float(sample), ensure_ascii=False, separators=(",", ":")).encode(
            "utf-8"
        )
    )


def split_signal_into_byte_chunks(
    signal: np.ndarray, target_chunk_bytes: int
) -> list[tuple[int, int]]:
    """
    Split signal into variable-size chunks based on approximate JSON payload bytes.

    The estimate follows JSON array representation: `[s1,s2,...]`.
    """
    if target_chunk_bytes <= 64:
        raise ValueError("target_chunk_bytes must be > 64")
    if len(signal) == 0:
        return []

    ranges: list[tuple[int, int]] = []
    chunk_start = 0
    current_bytes = 2  # '[' + ']'
    current_count = 0

    for idx, value in enumerate(signal):
        token_bytes = _json_token_size(float(value))
        add_bytes = token_bytes + (1 if current_count > 0 else 0)

        if current_count > 0 and (current_bytes + add_bytes) > target_chunk_bytes:
            ranges.append((chunk_start, idx))
            chunk_start = idx
            current_bytes = 2 + token_bytes
            current_count = 1
        else:
            current_bytes += add_bytes
            current_count += 1

    if current_count > 0:
        ranges.append((chunk_start, len(signal)))

    if len(ranges) > MAX_CHUNKS_PER_SIGNAL:
        merged: list[tuple[int, int]] = []
        merge_step = int(math.ceil(len(ranges) / MAX_CHUNKS_PER_SIGNAL))
        for i in range(0, len(ranges), merge_step):
            start = ranges[i][0]
            end = ranges[min(i + merge_step - 1, len(ranges) - 1)][1]
            merged.append((start, end))
        ranges = merged

    return ranges


def build_producer(kafka_bootstrap: str, retries: int = 8) -> KafkaProducer:
    """Create KafkaProducer with at-least-once delivery settings."""
    last_error: Exception | None = None

    for attempt in range(1, retries + 1):
        try:
            producer = KafkaProducer(
                bootstrap_servers=kafka_bootstrap,
                # acks=all은 broker가 저장 확인을 줄 때까지 성공 처리하지 않아 유실 가능성을 낮춘다.
                acks="all",
                # 일시적인 broker/network 문제는 Producer가 자동 재시도한다.
                retries=10,
                retry_backoff_ms=500,
                request_timeout_ms=30000,
                # 같은 연결에서 여러 요청이 앞질러 가는 것을 막아 chunk 순서 설명이 쉬워진다.
                max_in_flight_requests_per_connection=1,
                compression_type=os.getenv("KAFKA_COMPRESSION", "gzip"),
                linger_ms=20,
                batch_size=65536,
                max_request_size=MAX_REQUEST_SIZE,
                key_serializer=lambda value: value.encode("utf-8"),
                value_serializer=lambda value: json.dumps(
                    value, ensure_ascii=False, separators=(",", ":")
                ).encode("utf-8"),
            )
            logger.info("Connected to Kafka bootstrap=%s", kafka_bootstrap)
            return producer
        except NoBrokersAvailable as exc:
            last_error = exc
            logger.warning(
                "Kafka is not ready. attempt=%s/%s bootstrap=%s",
                attempt,
                retries,
                kafka_bootstrap,
            )
            time.sleep(3)

    raise RuntimeError(f"failed to connect to Kafka: {last_error}")


def on_send_success(metadata) -> None:
    logger.debug(
        "sent topic=%s partition=%s offset=%s",
        metadata.topic,
        metadata.partition,
        metadata.offset,
    )


def on_send_error(exc: KafkaError) -> None:
    logger.error("Kafka send failed: %s", exc)


def make_publish_items(
    records: list[ProductRecord],
    target_products: int,
    max_products: int | None,
    line_count: int,
    line_interval_seconds: float,
    line_seeds: list[int] | None = None,
) -> list[PublishItem]:
    """Create line-aware replay items for demo/load-test scenarios.

    line_seeds: 각 생산라인이 제품을 전송하는 순서를 결정하는 random seed 목록.
                길이가 line_count보다 짧으면 순환 사용한다.
                None이면 원래 정렬 순서 그대로 사용한다.
    """
    selected = records[:max_products] if max_products else records
    if not selected:
        return []

    if line_count < 1:
        raise ValueError("line_count must be >= 1")

    # 라인별로 제품 순서를 셔플한다 (seed가 주어진 경우).
    per_line_records: list[list[ProductRecord]] = []
    for line_index in range(line_count):
        shuffled = list(selected)
        if line_seeds:
            seed = line_seeds[line_index % len(line_seeds)]
            rng = random.Random(seed)
            rng.shuffle(shuffled)
        per_line_records.append(shuffled)

    total_products = target_products if target_products > 0 else len(selected) * line_count
    items: list[PublishItem] = []
    base_event_time = selected[0].event_time

    for index in range(total_products):
        line_index = index % line_count
        line_number = line_index + 1
        product_index = index // line_count
        line_pool = per_line_records[line_index]
        source = line_pool[product_index % len(line_pool)]
        line_id = source.line_id if line_count == 1 else f"LINE_{line_index + 1:02d}"
        if line_count == 1:
            line_number = line_number_from_line_id(line_id)
        is_replay = product_index >= len(line_pool) or line_id != source.line_id
        replay_no = product_index // len(line_pool)
        product_instance_id = (
            source.product_instance_id
            if not is_replay
            else f"{source.product_instance_id}_{line_id}_R{replay_no:05d}"
        )

        items.append(
            PublishItem(
                record=source,
                product_instance_id=product_instance_id,
                line_id=line_id if is_replay else source.line_id,
                line_number=line_number,
                event_time=base_event_time
                + timedelta(seconds=product_index * line_interval_seconds),
                is_duplicate=is_replay,
                original_product_instance_id=source.product_instance_id,
                replay_iteration=replay_no,
            )
        )

    return sorted(items, key=lambda item: (item.event_time, item.line_id, item.product_instance_id))


def publish_product(
    producer: KafkaProducer,
    item: PublishItem,
    topic: str,
    topic_laser_a: str | None,
    topic_laser_b: str | None,
    chunk_size: int,
    target_chunk_bytes: int | None,
    speed: float,
) -> int:
    """Publish all available leads/channels for one product instance."""
    sent = 0
    record = item.record
    topic_by_channel = {
        0: topic_laser_b or topic,
        1: topic_laser_a or topic,
    }

    for lead_num in sorted(record.leads_present):
        # 한 제품 안에서 laser_b(channel 0), laser_a(channel 1)를 순서대로 발행한다.
        for channel in (0, 1):
            file_path = record.files[channel].get(lead_num)
            if file_path is None:
                logger.warning(
                    "Missing channel. product=%s lead=%s channel=%s",
                    item.product_instance_id,
                    lead_num,
                    channel,
                )
                continue

            try:
                signal = load_signal(file_path)
            except Exception as exc:
                logger.error("Failed to load %s: %s", file_path, exc)
                continue

            _ = chunk_size  # backward compatibility for CLI argument.
            target_bytes = target_chunk_bytes or TARGET_CHUNK_BYTES
            chunk_ranges = split_signal_into_byte_chunks(
                signal, target_chunk_bytes=target_bytes
            )
            if not chunk_ranges:
                logger.warning(
                    "No chunk generated. product=%s lead=%s channel=%s",
                    item.product_instance_id,
                    lead_num,
                    channel,
                )
                continue
            total_chunks = len(chunk_ranges)
            chan_code = channel_code(channel)
            # partition key에 line/product/lead/laser를 넣어 같은 신호의 chunk가 같은 파티션에 쌓이게 한다.
            partition_key = (
                f"{item.line_id}_{item.product_instance_id}_"
                f"L{lead_num:02d}_{chan_code}"
            )

            for chunk_index, (chunk_start, chunk_end) in enumerate(chunk_ranges):
                # 큰 CSV 전체를 한 메시지로 보내지 않고 chunk로 나눠 broker/message size 부담을 줄인다.
                message = make_message(
                    item=item,
                    lead_num=lead_num,
                    channel=channel,
                    file_path=file_path,
                    samples=signal,
                    chunk_index=chunk_index,
                    total_chunks=total_chunks,
                    chunk_start=chunk_start,
                    chunk_end=chunk_end,
                )
                target_topic = topic_by_channel[channel]
                producer.send(target_topic, key=partition_key, value=message).add_callback(
                    on_send_success
                ).add_errback(on_send_error)
                sent += 1

                if speed > 0:
                    # speed는 "제품 간격"이 아니라 한 제품 내부 신호 chunk의 재생 속도이다.
                    delay_seconds = ((chunk_end - chunk_start) / SAMPLE_RATE_HZ) / speed
                    if delay_seconds >= 0.002:
                        time.sleep(delay_seconds)

    return sent


def run(args: argparse.Namespace) -> int:
    # Set up file logger before proceeding
    setup_file_logger(args.storage_dir)

    # 실행 흐름: 스캔 -> replay 목록 생성 -> dry-run 출력 또는 Kafka 발행.
    records = scan_data_dir(args.data_dir)
    if args.only_complete:
        records = [record for record in records if record.is_complete]
        logger.info("Filtered to complete product instances: %s", len(records))

    # --oldest-date-only: 가장 오래된 event_date의 제품만 선택한다.
    if args.oldest_date_only and records:
        oldest_date = min(r.event_time.date() for r in records)
        records = [r for r in records if r.event_time.date() == oldest_date]
        logger.info(
            "Filtered to oldest date %s: %s product instances", oldest_date, len(records)
        )

    if not records:
        logger.error("No matching product files found.")
        return 2

    # --line-seed: "1,2,3" 형식의 문자열을 정수 리스트로 변환한다.
    line_seeds: list[int] | None = None
    if args.line_seed:
        try:
            line_seeds = [int(s.strip()) for s in args.line_seed.split(",")]
        except ValueError:
            logger.error("--line-seed must be comma-separated integers, e.g. '1,2,3'")
            return 1

    items = make_publish_items(
        records=records,
        target_products=args.target_products,
        max_products=args.max_products,
        line_count=args.line_count,
        line_interval_seconds=args.line_interval_seconds,
        line_seeds=line_seeds,
    )

    if args.dry_run:
        original_count = sum(1 for item in items if not item.is_duplicate)
        duplicate_count = sum(1 for item in items if item.is_duplicate)
        lines = sorted({item.line_id for item in items})
        print("Dry run summary")
        print(f"- data_dir: {args.data_dir}")
        print(f"- storage_dir: {args.storage_dir or '(not configured)'}")
        print(f"- product_instances: {len(items)}")
        print(f"- originals: {original_count}")
        print(f"- duplicates: {duplicate_count}")
        print(f"- lines: {', '.join(lines)}")
        print(f"- line_count: {args.line_count}")
        print(f"- line_interval_seconds: {args.line_interval_seconds}")
        print(f"- topic_laser_a: {args.topic_laser_a or args.topic}")
        print(f"- topic_laser_b: {args.topic_laser_b or args.topic}")
        return 0

    producer = build_producer(args.kafka)

    try:
        while True:
            total_messages = 0
            first_event_time = items[0].event_time
            started_at = time.monotonic()
            for index, item in enumerate(items, start=1):
                if not args.no_schedule_wait:
                    # event_time 차이를 wall-clock 대기로 바꿔
                    # "각 생산라인에서 10초마다 CSV 생성" 상황을 시뮬레이션한다.
                    scheduled_after = (
                        item.event_time - first_event_time
                    ).total_seconds()
                    wait_seconds = scheduled_after - (time.monotonic() - started_at)
                    if wait_seconds > 0:
                        time.sleep(wait_seconds)

                pub_start = time.monotonic()
                sent = publish_product(
                    producer=producer,
                    item=item,
                    topic=args.topic,
                    topic_laser_a=args.topic_laser_a,
                    topic_laser_b=args.topic_laser_b,
                    chunk_size=args.chunk_size,
                    target_chunk_bytes=args.target_chunk_bytes,
                    speed=args.speed,
                )
                pub_elapsed = time.monotonic() - pub_start
                total_messages += sent
                msg_per_sec = sent / pub_elapsed if pub_elapsed > 0 else 0.0

                logger.info(
                    "[%s/%s] product=%s line=%s duplicate=%s messages=%s elapsed_ms=%.2f msg_per_sec=%.2f",
                    index,
                    len(items),
                    item.product_instance_id,
                    item.line_id,
                    item.is_duplicate,
                    sent,
                    pub_elapsed * 1000,
                    msg_per_sec,
                )

            producer.flush()
            total_elapsed = time.monotonic() - started_at
            avg_msg_per_sec = total_messages / total_elapsed if total_elapsed > 0 else 0.0
            
            # flush 이후 종료해야 Python 프로세스가 끝나기 전에 buffered message가 모두 전송된다.
            logger.info(
                "Run complete. total_messages=%s total_elapsed_sec=%.2f avg_msg_per_sec=%.2f", 
                total_messages, total_elapsed, avg_msg_per_sec
            )

            if not args.loop:
                break
            logger.info("Loop mode enabled. Restarting replay in 5 seconds.")
            time.sleep(5)
    except KeyboardInterrupt:
        logger.info("Interrupted by user.")
    finally:
        producer.flush()
        producer.close()
        logger.info("Producer closed.")

    return 0


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    # CLI 옵션은 실험 조건을 바꾸는 부분이다. 코드 수정 없이 라인 수/속도/목표 제품 수를 조절한다.
    parser = argparse.ArgumentParser(
        description="Welding CSV to Kafka producer",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--data-dir",
        default=DEFAULT_DATA_DIR,
        required=DEFAULT_DATA_DIR is None,
        help="CSV root directory. Defaults to DATA_DIR from .env",
    )
    parser.add_argument(
        "--storage-dir",
        default=DEFAULT_STORAGE_DIR,
        help="Future output/archive root directory. Defaults to STORAGE_DIR from .env",
    )
    parser.add_argument("--kafka", default=DEFAULT_KAFKA, help="Kafka bootstrap server")
    parser.add_argument(
        "--topic",
        default=TOPIC_RAW,
        help="Fallback Kafka topic used when per-channel topics are not set.",
    )
    parser.add_argument(
        "--topic-laser-a",
        default=TOPIC_RAW_LASER_A or None,
        help="Kafka topic for Laser A (channel=1). Defaults to --topic when omitted.",
    )
    parser.add_argument(
        "--topic-laser-b",
        default=TOPIC_RAW_LASER_B or None,
        help="Kafka topic for Laser B (channel=0). Defaults to --topic when omitted.",
    )
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=DEFAULT_CHUNK_SIZE,
        help="Deprecated compatibility option. Chunking uses TARGET_CHUNK_BYTES.",
    )
    parser.add_argument(
        "--target-chunk-bytes",
        type=int,
        default=TARGET_CHUNK_BYTES,
        help="Target JSON payload size (bytes) per chunk.",
    )
    parser.add_argument("--speed", type=float, default=50.0, help="Replay speed multiplier")
    parser.add_argument(
        "--line-count",
        type=int,
        default=1,
        help="Number of production lines to simulate",
    )
    parser.add_argument(
        "--line-interval-seconds",
        type=float,
        default=10.0,
        help="Seconds between products from each production line",
    )
    parser.add_argument(
        "--no-schedule-wait",
        action="store_true",
        help="Do not wait for the simulated line interval; publish as fast as chunk speed allows",
    )
    parser.add_argument(
        "--target-products",
        type=int,
        default=0,
        help="Replay duplicate product instances until this count is reached",
    )
    parser.add_argument(
        "--max-products",
        type=int,
        default=None,
        help="Limit original product instances for a short demo",
    )
    parser.add_argument(
        "--only-complete",
        action="store_true",
        help="Publish only products with 16 Laser A/B lead pairs",
    )
    parser.add_argument("--loop", action="store_true", help="Replay continuously")
    parser.add_argument("--dry-run", action="store_true", help="Scan and print summary only")
    parser.add_argument(
        "--oldest-date-only",
        action="store_true",
        help="Use only product instances from the oldest date folder found in data_dir",
    )
    parser.add_argument(
        "--line-seed",
        default=None,
        help="Comma-separated random seeds for per-line shuffle, e.g. '1,2,3'",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(run(parse_args()))

